# Cumin main configuration
#
# By default Cumin load the configuration from /etc/cumin/config.yaml, but it can be overriden by command line argument
#
transport: clustershell  # Default transport to use, can be overriden by command line argument
log_file: logs/cumin.log  # Absolute or relative path for the log file
# If set, use this backend to parse the query first and only if it fails, fallback to parse it with the general
# multi-query grammar [optional]
default_backend: direct

# Environment variables that will be defined [optional]
environment:
    ENV_VARIABLE: env_value

# Backend-specific configurations [optional]
ec2:
    access_key_id: key_id
    secret_access_key: access_key
    region: eu-west-1
    profile: default
    address_type: PublicDnsName

# Transport-specific configuration
clustershell:
    ssh_user: 'ubuntu'  # SSH options passed to ClusterShell [optional]
    fanout: 16  # Max size of the sliding window of concurrent workers active at any given time [optional, default: 64]

# Plugins-specific configuration
plugins:
    backends:  # External backends. Each module must define GRAMMAR_PREFIX and query_class, and be in Python PATH
        - cumin_backend_ec2
